/*Anime Stats
  Copyright (C) 2015-2018 Thomas Sweeney
  This file is part of Anime Stats.
  Anime Stats is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  Anime Stats is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/

#include <string>
#include <vector>
#include "CreateCommands.hpp"

namespace SqlStrings
{
    const std::vector<std::string> createCommands =
    {
        {
            //create.sql
            "CREATE TABLE \"WatchedStatus\" (\n"
            "  \"idWatchedStatus\" INTEGER PRIMARY KEY,\n"
            "  \"status\" TEXT NOT NULL\n"
            ");\n"
            "INSERT INTO `WatchedStatus` VALUES (0,'');\n"
            "INSERT INTO `WatchedStatus` VALUES (1,'Watched');\n"
            "INSERT INTO `WatchedStatus` VALUES (2,'Watching');\n"
            "INSERT INTO `WatchedStatus` VALUES (3,'Stalled');\n"
            "INSERT INTO `WatchedStatus` VALUES (4,'Dropped');\n"
            "INSERT INTO `WatchedStatus` VALUES (5,'To Watch');\n"
            "CREATE TABLE \"Title\" (\n"
            "	`idName`	INTEGER,\n"
            "	`name`	TEXT NOT NULL,\n"
            "	`idSeries`	INTEGER NOT NULL,\n"
            "	`idLabel`	INTEGER NOT NULL DEFAULT 0,\n"
            "	`Pronunciation`	TEXT,\n"
            "	PRIMARY KEY(idName),\n"
            "	FOREIGN KEY(`idSeries`) REFERENCES `Series`(`idSeries`) ON DELETE CASCADE ON UPDATE CASCADE,\n"
            "	FOREIGN KEY(`idLabel`) REFERENCES `Label`(`idLabel`) ON DELETE SET DEFAULT ON UPDATE CASCADE\n"
            ");\n"
            "CREATE TABLE \"Series\" (\n"
            "	`idSeries`	INTEGER,\n"
            "	`rating`	INTEGER DEFAULT NULL,\n"
            "	`idReleaseType`	INTEGER DEFAULT 0,\n"
            "	`idWatchedStatus`	INTEGER DEFAULT 0,\n"
            "	`year`	INTEGER DEFAULT NULL,\n"
            "	`idSeason`	INTEGER DEFAULT 0,\n"
            "	`episodesWatched`	INTEGER DEFAULT NULL,\n"
            "	`totalEpisodes`	INTEGER DEFAULT NULL,\n"
            "	`rewatchedEpisodes`	INTEGER DEFAULT NULL,\n"
            "	`episodeLength`	INTEGER DEFAULT NULL,\n"
            "	`dateStarted`	TEXT DEFAULT NULL,\n"
            "	`dateFinished`	TEXT DEFAULT NULL,\n"
            "	PRIMARY KEY(idSeries),\n"
            "	FOREIGN KEY(`idReleaseType`) REFERENCES \"ReleaseType\" ( \"idReleaseType\" ) ON DELETE NO ACTION ON UPDATE NO ACTION,\n"
            "	FOREIGN KEY(`idWatchedStatus`) REFERENCES \"WatchedStatus\" ( \"idWatchedStatus\" ) ON DELETE NO ACTION ON UPDATE NO ACTION,\n"
            "	FOREIGN KEY(`idSeason`) REFERENCES \"Season\" ( \"idSeason\" ) ON DELETE NO ACTION ON UPDATE NO ACTION\n"
            ");\n"
            "CREATE TABLE \"Season\" (\n"
            "  \"idSeason\" INTEGER PRIMARY KEY,\n"
            "  \"season\" TEXT DEFAULT NULL\n"
            ");\n"
            "INSERT INTO `Season` VALUES (0,'');\n"
            "INSERT INTO `Season` VALUES (1,'Winter');\n"
            "INSERT INTO `Season` VALUES (2,'Spring');\n"
            "INSERT INTO `Season` VALUES (3,'Summer');\n"
            "INSERT INTO `Season` VALUES (4,'Fall');\n"
            "CREATE TABLE \"ReleaseType\" (\n"
            "  \"idReleaseType\" INTEGER PRIMARY KEY,\n"
            "  \"type\" TEXT NOT NULL\n"
            ");\n"
            "INSERT INTO `ReleaseType` VALUES (0,'');\n"
            "INSERT INTO `ReleaseType` VALUES (1,'TV');\n"
            "INSERT INTO `ReleaseType` VALUES (2,'OVA');\n"
            "INSERT INTO `ReleaseType` VALUES (3,'ONA');\n"
            "INSERT INTO `ReleaseType` VALUES (4,'Movie');\n"
            "INSERT INTO `ReleaseType` VALUES (5,'TV Special');\n"
            "CREATE TABLE \"Label\" (\n"
            "	`idLabel`	INTEGER,\n"
            "	`label`	TEXT NOT NULL,\n"
            "	`Main`	INTEGER DEFAULT 0,\n"
            "	PRIMARY KEY(idLabel)\n"
            ");\n"
            "INSERT INTO `Label` VALUES (0,'No Label',0);\n"
            "INSERT INTO `Label` VALUES (1,'Default',1);\n"
            "CREATE TABLE \"Tag\" (\n"
            "    `idTag` INTEGER,\n"
            "    `idSeries` INTEGER NOT NULL,\n"
            "    `tag` TEXT NOT NULL,\n"
            "    `val` TEXT NOT NULL DEFAULT '',\n"
            "    PRIMARY KEY(`idTag`),\n"
            "    UNIQUE (idSeries, tag, val),\n"
            "    FOREIGN KEY(`idSeries`) REFERENCES \"Series\" ( \"idSeries\" ) ON DELETE CASCADE ON UPDATE CASCADE\n"
            ");\n"
        },
        //create_p1.sql
        {
            "CREATE TABLE \"Version\" (\n"
            "    `version` INTEGER NOT NULL\n"
            ");\n"
            "INSERT INTO `Version` VALUES (1);\n"
            "\n"
            "CREATE TABLE \"SavedFilter\" (\n"
            "    `idSavedFilter` INTEGER,\n"
            "    `name` TEXT NOT NULL,\n"
            "    `default` INTEGER NOT NULL,\n"
            "    PRIMARY KEY(`idSavedFilter`),\n"
            "    UNIQUE (`name`)\n"
            ");\n"
            "INSERT INTO `SavedFilter` VALUES (0, 'All', 1);\n"
            "INSERT INTO `SavedFilter` VALUES (1, 'Watched', 0);\n"
            "INSERT INTO `SavedFilter` VALUES (2, 'Watching', 0);\n"
            "INSERT INTO `SavedFilter` VALUES (3, 'Stalled', 0);\n"
            "INSERT INTO `SavedFilter` VALUES (4, 'Dropped', 0);\n"
            "INSERT INTO `SavedFilter` VALUES (5, 'To Watch', 0);\n"
            "INSERT INTO `SavedFilter` VALUES (6, 'Blank', 0);\n"
            "CREATE TABLE \"SavedFilterArgName\" (\n"
            "    `idSavedFilterArgName` INTEGER,\n"
            "    `name` TEXT,\n"
            "    PRIMARY KEY(`idSavedFilterArgName`),\n"
            "    UNIQUE (`name`)\n"
            ");\n"
            "INSERT INTO `SavedFilterArgName` VALUES (0, 'watched');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (1, 'watching');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (2, 'stalled');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (3, 'dropped');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (4, 'toWatch');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (5, 'blank');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (6, 'tv');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (7, 'movie');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (8, 'ova');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (9, 'ona');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (10, 'tvSpecial');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (11, 'releaseBlank');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (12, 'winter');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (13, 'spring');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (14, 'summer');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (15, 'fall');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (16, 'seasonBlank');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (17, 'ratingEnabled');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (18, 'yearEnabled');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (19, 'epsWatchedEnabled');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (20, 'epsRewatchedEnabled');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (21, 'totalEpsEnabled');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (22, 'lengthEnabled');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (23, 'dateStartedEnabled');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (24, 'dateFinishedEnabled');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (25, 'ratingLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (26, 'ratingHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (27, 'yearLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (28, 'yearHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (29, 'epsWatchedLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (30, 'epsWatchedHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (31, 'epsRewatchedLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (32, 'epsRewatchedHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (33, 'totalEpsLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (34, 'totalEpsHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (35, 'lengthLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (36, 'lengthHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (37, 'yearStartedLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (38, 'yearStartedHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (39, 'monthStartedLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (40, 'monthStartedHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (41, 'dayStartedLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (42, 'dayStartedHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (43, 'yearFinishedLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (44, 'yearFinishedHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (45, 'monthFinishedLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (46, 'monthFinishedHigh');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (47, 'dayFinishedLow');\n"
            "INSERT INTO `SavedFilterArgName` VALUES (48, 'dayFinishedHigh');\n"
            "CREATE TABLE \"SavedFilterArg\" (\n"
            "    `idSavedFilterArg` INTEGER,\n"
            "    `idSavedFilter` INTEGER NOT NULL,\n"
            "    `idSavedFilterArgName` INTEGER NOT NULL,\n"
            "    `value` INTEGER NOT NULL,\n"
            "    PRIMARY KEY (`idSavedFilterArg`),\n"
            "    FOREIGN KEY (`idSavedFilter`) REFERENCES \"SavedFilter\" ( \"idSavedFilter\" )\n"
            "        ON DELETE CASCADE ON UPDATE CASCADE,\n"
            "    FOREIGN KEY (`idSavedFilterArgName`)\n"
            "        REFERENCES \"SavedFilterArgName\" ( \"idSavedFilterArgName\" )\n"
            "        ON DELETE CASCADE ON UPDATE CASCADE,\n"
            "    UNIQUE (`idSavedFilter`, `idSavedFilterArgName`)\n"
            ");\n"
            "INSERT INTO `SavedFilterArg` VALUES (0, 1, 0, 1);\n"
            "INSERT INTO `SavedFilterArg` VALUES (1, 1, 1, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (2, 1, 2, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (3, 1, 3, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (4, 1, 4, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (5, 1, 5, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (6, 2, 0, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (7, 2, 1, 1);\n"
            "INSERT INTO `SavedFilterArg` VALUES (8, 2, 2, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (9, 2, 3, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (10, 2, 4, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (11, 2, 5, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (12, 3, 0, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (13, 3, 1, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (14, 3, 2, 1);\n"
            "INSERT INTO `SavedFilterArg` VALUES (15, 3, 3, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (16, 3, 4, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (17, 3, 5, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (18, 4, 0, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (19, 4, 1, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (20, 4, 2, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (21, 4, 3, 1);\n"
            "INSERT INTO `SavedFilterArg` VALUES (22, 4, 4, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (23, 4, 5, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (24, 5, 0, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (25, 5, 1, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (26, 5, 2, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (27, 5, 3, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (28, 5, 4, 1);\n"
            "INSERT INTO `SavedFilterArg` VALUES (29, 5, 5, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (30, 6, 0, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (31, 6, 1, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (32, 6, 2, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (33, 6, 3, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (34, 6, 4, 0);\n"
            "INSERT INTO `SavedFilterArg` VALUES (35, 6, 5, 1);\n"
        },
        //create_p2.sql
        {
            "UPDATE `Version` set `version` = 2;\n"
            "\n"
            "CREATE TABLE \"SavedFilterSortName\" (\n"
            "    `idSavedFilterSortName` INTEGER,\n"
            "    `name` TEXT NOT NULL,\n"
            "    PRIMARY KEY (`idSavedFilterSortName`),\n"
            "    UNIQUE (`name`)\n"
            ");\n"
            "INSERT INTO `SavedFilterSortName` (`idSavedFilterSortName`, `name`) VALUES\n"
            "    (1, 'nameSort'),\n"
            "    (2, 'Rating'),\n"
            "    (3, 'Watched Status'),\n"
            "    (4, 'Release Type'),\n"
            "    (5, 'Year'),\n"
            "    (6, 'Season'),\n"
            "    (7, 'Episodes Watched'),\n"
            "    (8, 'Total Episodes'),\n"
            "    (9, 'Rewatched Episodes'),\n"
            "    (10, 'Episode Length'),\n"
            "    (11, 'Date Started'),\n"
            "    (12, 'Date Finished');\n"
            "\n"
            "CREATE TABLE \"SavedFilterSort\" (\n"
            "    `idSavedFilterSort` INTEGER,\n"
            "    `idSavedFilter` INTEGER NOT NULL,\n"
            "    `idSavedFilterSortName` INTEGER NOT NULL,\n"
            "    `asc` INTEGER NOT NULL,\n"
            "    PRIMARY KEY (`idSavedFilterSort`),\n"
            "    UNIQUE (`idSavedFilter`, `idSavedFilterSortName`),\n"
            "    FOREIGN KEY (`idSavedFilter`) REFERENCES \"SavedFilter\" ( \"idSavedFilter\" )\n"
            "        ON DELETE CASCADE ON UPDATE CASCADE,\n"
            "    FOREIGN KEY (`idSavedFilterSortName`) REFERENCES\n"
            "        \"SavedFilter\" ( \"idSavedFilter\" ) ON DELETE CASCADE ON UPDATE CASCADE\n"
            ");\n"
        },
        //create_p3.sql
        {
            "PRAGMA foreign_keys=off;\n"
            "\n"
            "UPDATE `Version` set `version` = 3;\n"
            "\n"
            "ALTER TABLE `SavedFilterSort` RENAME TO `SavedFilterSort_old`;\n"
            "\n"
            "CREATE TABLE \"SavedFilterSort\" (\n"
            "    `idSavedFilterSort` INTEGER,\n"
            "    `idSavedFilter` INTEGER NOT NULL,\n"
            "    `idSavedFilterSortName` INTEGER NOT NULL,\n"
            "    `asc` INTEGER NOT NULL,\n"
            "    PRIMARY KEY (`idSavedFilterSort`),\n"
            "    UNIQUE (`idSavedFilter`, `idSavedFilterSortName`),\n"
            "    FOREIGN KEY (`idSavedFilter`) REFERENCES \"SavedFilter\" ( \"idSavedFilter\" )\n"
            "        ON DELETE CASCADE ON UPDATE CASCADE,\n"
            "    FOREIGN KEY (`idSavedFilterSortName`) REFERENCES\n"
            "        \"SavedFilterSortName\" ( \"idSavedFilterSortName\" )\n"
            "        ON DELETE CASCADE ON UPDATE CASCADE\n"
            ");\n"
            "\n"
            "INSERT INTO `SavedFilterSort` SELECT * FROM `SavedFilterSort_old`;\n"
            "DROP TABLE `SavedFilterSort_old`;\n"
            "\n"
            "PRAGMA foreign_keys=on;"
        },
        //create_p4.sql
        {
            "UPDATE `Version` set `version` = 4;\n"
            "INSERT INTO `SavedFilterSortName` (`name`) VALUES ('Pronunciation');"
        },
        //create_p5.sql
        {
            "UPDATE `Version` set `version` = 5;\n"
            "INSERT INTO `SavedFilterArgName` (name) VALUES\n"
            "    ('tagEnabled'),\n"
            "    ('tagInverse'),\n"
            "    ('tag'),\n"
            "    ('tagValEnabled'),\n"
            "    ('tagValInserse'),\n"
            "    ('tagVal')\n"
        }
    };
}
